// Package main: clashprofile.go
//
// Rebuilds an upstream Clash profile (JustMySocks' `getsub.php?...&format=clash`
// output) around this project's policy.
//
// Division of responsibility:
//   - the provider owns `proxies:` — node fields, ciphers, REALITY keys and
//     UDP declarations pass through byte-for-byte, so new protocols need no
//     code change here and we never assert a capability upstream did not
//     advertise;
//   - this project owns everything else — a single `PROXY` select group,
//     the loopback guard, project rules, Loyalsoldier rule-providers, DNS
//     and TUN.
//
// Client-level keys the provider ships (mixed-port, allow-lan, mode,
// log-level, ipv6) are dropped: clash-verge-rev manages those itself, and
// the vendor's `ipv6: false` would silently contradict our DNS block.
package main

import (
	"errors"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// masterGroupName must stay "PROXY": project rules and the Loyalsoldier
// rule chain both target it by name.
const masterGroupName = "PROXY"

// looksLikeClashProfile reports whether the upstream body is already a Clash
// YAML profile rather than a base64 link bundle. Base64 alphabets contain no
// ':', so a `proxies:` key cannot appear in an encoded subscription.
func looksLikeClashProfile(raw string) bool {
	for _, line := range strings.Split(raw, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "proxies:") {
			return true
		}
	}
	return false
}

// mappingValue returns the scalar value for `key` in a YAML mapping node.
func mappingValue(node *yaml.Node, key string) string {
	if node == nil || node.Kind != yaml.MappingNode {
		return ""
	}
	for i := 0; i+1 < len(node.Content); i += 2 {
		if node.Content[i].Value == key {
			return node.Content[i+1].Value
		}
	}
	return ""
}

// orderProxyNames moves the first name matching `match` (case-insensitive
// substring) to the front so it becomes the group's default selection.
func orderProxyNames(names []string, match string) []string {
	if match == "" {
		return names
	}
	needle := strings.ToLower(match)
	for i, n := range names {
		if strings.Contains(strings.ToLower(n), needle) {
			out := make([]string, 0, len(names))
			out = append(out, n)
			out = append(out, names[:i]...)
			out = append(out, names[i+1:]...)
			return out
		}
	}
	return names
}

// ConvertClashProfile converts an upstream Clash profile into this project's
// profile. Returns an error if the upstream carries no usable proxies.
func ConvertClashProfile(raw string, opts ConvertOptions) (string, error) {
	if opts.RuleProvidersBaseURL == "" {
		opts.RuleProvidersBaseURL = defaultLoyalsoldierBaseURL
	}

	// Decode only `proxies:` and keep it as a raw node — anything we round
	// -trip through a Go struct would lose fields we do not know about.
	var upstream struct {
		Proxies yaml.Node `yaml:"proxies"`
	}
	if err := yaml.Unmarshal([]byte(raw), &upstream); err != nil {
		return "", fmt.Errorf("parse upstream clash profile: %w", err)
	}
	proxiesNode := &upstream.Proxies
	if proxiesNode.Kind != yaml.SequenceNode || len(proxiesNode.Content) == 0 {
		return "", errors.New("upstream clash profile contains no proxies")
	}

	names := make([]string, 0, len(proxiesNode.Content))
	for _, p := range proxiesNode.Content {
		if n := mappingValue(p, "name"); n != "" {
			names = append(names, n)
		}
	}
	if len(names) == 0 {
		return "", errors.New("upstream clash profile has proxies but none carry a name")
	}

	// One select group. DIRECT/REJECT are Clash built-ins — rules reach them
	// without any group, so listing them here purely adds a manual
	// bypass-all / block-all switch in the client UI.
	members := make([]any, 0, len(names)+2)
	for _, n := range orderProxyNames(names, opts.DefaultProxyMatch) {
		members = append(members, forceStr(n))
	}
	members = append(members, "DIRECT", "REJECT")
	groups := []map[string]any{{
		"name":    masterGroupName,
		"type":    "select",
		"proxies": members,
	}}
	groupsSeq, err := toYAMLNode(groups)
	if err != nil {
		return "", fmt.Errorf("build proxy-groups: %w", err)
	}

	root := &yaml.Node{Kind: yaml.MappingNode}
	if opts.DNS.hasContent() {
		root.Content = append(root.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: "dns"}, buildDNSNode(opts.DNS),
		)
	}
	if opts.Tun.hasContent() {
		root.Content = append(root.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: "tun"}, buildTunNode(opts.Tun),
		)
	}
	root.Content = append(root.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "proxies"}, proxiesNode,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "proxy-groups"}, groupsSeq,
	)

	out, err := yaml.Marshal(root)
	if err != nil {
		return "", fmt.Errorf("marshal profile: %w", err)
	}

	return "# Auto-generated by AutoConvJmsSub from the provider's Clash subscription.\n" +
		"# Nodes come from upstream untouched; groups, rules, DNS and TUN are project-managed.\n" +
		"# Default rules use Loyalsoldier rule-providers (https://github.com/Loyalsoldier/clash-rules).\n\n" +
		string(out) +
		buildRulesAndProvidersYAML(opts.RuleProvidersEnabled, opts.RuleProvidersBaseURL, opts.PrependRules), nil
}
